version: '2'
services:
    client-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/client/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=client
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
